<?php
// view_file.php - Formal Report View
require_once 'db_connection.php';

if (isset($_GET['id'])) {
    $id = intval($_GET['id']);
    $query = "SELECT * FROM reports WHERE id = $id";
    $result = mysqli_query($conn, $query);
    
    if ($row = mysqli_fetch_assoc($result)) {
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report - <?php echo htmlspecialchars($row['report_no']); ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="css/style_report_view.css">
</head>
<body>

    <div class="back-nav">
        <a href="admin.php" class="btn-back">
            <i class="fas fa-arrow-left"></i> Back to Dashboard
        </a>
    </div>

    <div class="report-paper">
        <div class="report-header">
            <div class="company-logo">
                <i class="fas fa-clipboard-check"></i> APG SAFETY SYSTEM
            </div>
            <div class="report-id">
                <p><strong>Report No:</strong> <?php echo htmlspecialchars($row['report_no']); ?></p>
                <p><strong>Date Generated:</strong> <?php echo date('d M Y', strtotime($row['report_date'])); ?></p>
            </div>
        </div>

        <div class="report-section">
            <h2 style="font-size: 24px; color: #2c3e50; margin-bottom: 20px;"><?php echo htmlspecialchars($row['report_title']); ?></h2>
            <div class="info-grid">
                <div class="info-item">
                    <label>Identity Role</label>
                    <span><?php echo htmlspecialchars($row['role']); ?></span>
                </div>
                <div class="info-item">
                    <label>Review Status</label>
                    <span class="status-badge status-<?php echo strtolower(str_replace(' ', '-', $row['approval_status'])); ?>">
                        <?php echo htmlspecialchars($row['approval_status']); ?>
                    </span>
                </div>
            </div>
        </div>

        <div class="report-section">
            <div class="section-title">Inspection Findings</div>
            <div class="description-box">
                <?php echo nl2br(htmlspecialchars($row['description'])); ?>
            </div>
        </div>

        <div class="report-section">
            <div class="section-title">Document Reference</div>
            <div class="info-item">
                <label>Database Path Reference</label>
                <span style="color: #3498db;"><i class="fas fa-file-pdf"></i> <?php echo htmlspecialchars($row['file_path']); ?></span>
            </div>
        </div>

        <?php if (!empty($row['admin_notes'])): ?>
        <div class="report-section">
            <div class="section-title">Admin Review Notes</div>
            <div style="background: #fff5f5; padding: 15px; border-radius: 5px; color: #c0392b;">
                <strong>Remarks:</strong> <?php echo htmlspecialchars($row['admin_notes']); ?>
            </div>
        </div>
        <?php endif; ?>

        <div class="footer-note">
            Electronic document generated by APG Safety Management System. Confidentiality and security protocols apply.
        </div>
        
        <div style="margin-top: 30px; text-align: right;" class="back-nav">
            <button onclick="window.print()" class="btn-back" style="background: #3498db;">
                <i class="fas fa-print"></i> Print Report
            </button>
        </div>
    </div>

</body>
</html>
<?php
    } else {
        echo "<div style='text-align:center; padding:50px;'><h2>Report not found.</h2><a href='admin.php'>Return to Dashboard</a></div>";
    }
}
?>